Add desired resin input field
MadeBaruna/paimon-moe pull request #16
Opened 2021-03-19 10:33 UTC by fadhluu

2021-03-19 17:51 UTC, MadeBaruna commented
Please don't add more library for the time stuff. I have added dayjs before, so you can use it there

2021-03-19 17:53 UTC, MadeBaruna requested changes
Please remove svelte-countdown and svelte-time. You can already use dayjs for the countdown/duration.

2021-03-20 03:36 UTC, fadhluu commented
> Please remove svelte-countdown and svelte-time. You can already use dayjs for the countdown/duration.

Yeah my bad, didnt check the package first. I was about to remove the other package, but you already reviewed it. :+1:

2021-03-21 14:51 UTC, MadeBaruna approved these changes

2021-03-21 14:51 UTC, merged